FROM continuumio/miniconda3

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install linux & conda requirements
COPY . /
COPY /outsight/conda_env.yml .

RUN apt-get update && apt-get install make
RUN make install_os_requirements
RUN make create_conda_env

# Make RUN commands use the new environment
# https://pythonspeed.com/articles/activate-conda-dockerfile/
SHELL ["conda", "run", "-n", "outofsight", "/bin/bash", "-c"]

# ENTRYPOINT []
CMD ["conda", "run", "-n", "outofsight", "python", "/outsight/app.py"]