name: outofsight
channels:
  - defaults
  - conda-forge
dependencies:
  - blas=1.0
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - conda=4.11.0
  - conda-package-handling=1.7.3
  - cryptography=3.4.7
  - idna=2.10
  - intel-openmp=2021.4.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openssl=1.1.1m
  - packaging=20.4
  - pandas=1.3.5
  - pip=21.1.3
  - pycosat=0.6.3
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.9.5
  - python-dateutil=2.8.1
  - pytz=2020.1
  - requests=2.25.1
  - ruamel_yaml=0.15.100
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.0
  - tqdm=4.61.2
  - tzdata=2021e
  - urllib3=1.26.6
  - wheel=0.36.2
  - yaml=0.2.5
  - pip:
    - d6tcollect==1.0.6
    - d6tflow==0.2.5
    - docutils==0.18.1
    - imageio==2.14.1
    - imutils==0.5.4
    - lockfile==0.12.2
    - luigi==3.0.3
    - networkx==2.6.3
    - opencv-contrib-python==4.5.5.62
    - pillow==9.0.0
    - pyarrow==6.0.1
    - pytesseract==0.3.8
    - python-daemon==2.3.0
    - pywavelets==1.2.0
    - scikit-image==0.19.1
    - scipy==1.7.3
    - tenacity==6.3.1
    - tifffile==2021.11.2
    - tornado==6.1